### ISSUE TITLE
Cannot add testing due to babel syntax failures, we need to fix these imports

### ISSUE THREAD

**Issue by harshavardhana** [minio/miniobrowser#32]
A simple Login.spec.js test for mocha cannot be executed. 

```
$ cat app/tests/Login.spec.js
import React from 'react';
import TestUtils from 'react-addons-test-utils';
import expect from 'expect';

import Login from '../js/components/Login';

describe('Login', () => {
  it('should execute submit', () => {
    const renderer = TestUtils.createRenderer();
    renderer.render(<Login />);
    const actual = renderer.getRenderOutput();
    console.log(actual);
  });
});
``` 

```
> minio-browser@0.0.1 test /Users/harsha/Repositories/miniobrowser
> mocha './app/tests/*.spec.js' --compilers js:babel-core/register

Users/harsha/Repositories/miniobrowser/node_modules/babel-core/lib/transformation/file/index.js:548
      throw err;
            ^
SyntaxError: /Users/harsha/Repositories/miniobrowser/app/img/logo.svg: Unexpected token (1:1)
> 1 | <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    |  ^
  2 | <svg
  3 |    xmlns:dc="http://purl.org/dc/elements/1.1/"
  4 |    xmlns:cc="http://creativecommons.org/ns#"
    at Parser.pp.raise (/Users/harsha/Repositories/miniobrowser/node_modules/babel-core/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/Users/harsha/Repositories/miniobrowser/node_modules/babel-core/node_modules/babylon/index.js:2907:8)
    at Parser.pp.jsxParseIdentifier (/Users/harsha/Repositories/miniobrowser/node_modules/babel-core/node_modules/babylon/index.js:4180:10)
    at Parser.pp.jsxParseNamespacedName (/Users/harsha/Repositories/miniobrowser/node_modules/babel-core/node_modules/babylon/index.js:4191:19)
```

**Comment by harshavardhana** [comment]
Using karma + mocha fixes this problem, closing.
